# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "60370387e07d5f564cfca1e529047bff"
name = "babeeni: Verify Service"
handle = "babeeni-otp-app"
application_url = "https://twilio-b5a9c.web.app/app/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://twilio-b5a9c.web.app/api/auth/callback/"
]

[app_proxy]
url = "https://twilio-b5a9c.web.app/api/public/"
subpath = "babeeni-otp-app"
prefix = "apps"

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://twilio-b5a9c.web.app/api/webhooks/"

[pos]
embedded = false
